### PR TITLE
config do support Enum `TurnProvider`

### PR DESCRIPTION
**Pull request by louis1706**
Ì have seen other plugin using Enum

### CODE REVIEW

**Comment by DaXcess** [comment]
This works lol?!
I was trying to do enum based when making it but couldn't figure it out for the life of me lol.

I'll just quickly check if the config is string based then I'll merge

**Comment by DaXcess** [comment]
image

This one's annoying though, since it doesn't mention any options between Snap and Disabled (which only is Smooth, but still)

**Comment by louis1706** [comment]
> image
> 
> This one's annoying though, since it doesn't mention any options between Snap and Disabled (which only is Smooth, but still)

Now fixed :)

**Comment by DaXcess** [comment]
Added the actual `AcceptableValueEnum` that was brainstormed yesterday

**Pull request merged**
