### PR TITLE
Updated compilation instructions

### PR DESCRIPTION
**Pull request by AyOhEe**
COMPILATION.md did not mention that DissonanceVoip.dll was required, and also referenced `Libs/Managed` instead of `Libs`, so I figure this is a worthwhile addition.

### CODE REVIEW

**Comment by AyOhEe** [comment]
This would fix #15

**Comment by DINH-iy** [comment]
I agree

**Comment by AyOhEe** [comment]
Closing PR so I can just pull over the commit that actually addresses #15 , not anything else

**Comment by AyOhEe** [comment]
Whoops, wrong branch. Made a branch on my fork that has just this fix: look at #23 instead.

**Comment by AyOhEe** [comment]
Whoops, wrong branch. Made a branch on my fork that has just this fix: look at https://github.com/DaXcess/LCVR/pull/23 instead.

**Pull request closed without merging**
