### PR TITLE
Mimics compatibility: Offset mimic interact UI to be in the correct position

### PR DESCRIPTION
**Pull request by NickDuijndam**
This fixes the Interact UI when interacting with doors from the [Mimics mod](https://github.com/x753/Lethal-Company-Mimics). 

It adds an offset component to all mimic doors with the desired offset. This is then read out right before `UpdateInteractCanvasPosition` is called. 

I've mainly done it this way to not pollute the LCVR code with random mod patches, but it could be simplified by checking if the InteractTrigger's parent object is a mimic door directly in the `VRController` class. This patch might also not be desired in general since having soft dependencies on mods like this can get pretty tedious to maintain.

I would love to hear your opinion on this :)

### CODE REVIEW

**Comment by DaXcess** [comment]
Wow, this is almost exactly like how I would have written this!
And about the soft dependency stuff, I don't really know what the alternative would be, since just like MoreCompany, if this mod loads before them, the patches fail (and I'm not certain that HarmonyAfter works across different Harmony instances from different Assemblies).

**Comment by DaXcess** [comment]
Nevermind just read https://harmony.pardeike.net/articles/priorities.html, looks like this could make it so there are no soft dependencies required (though will test extensively to confirm this).

**Comment by NickDuijndam** [comment]
I'm not super familiar with modding and the workings of Harmony & bepinex but initially i forgot to add Mimics as a soft dependency which caused the patch to not be loaded because bepinex loaded LCVR before Mimics, and LCVRPatch checked the currently loaded bepinex plugins. 

So youre saying it might work without soft dependency if we just always apply the harmony patch? (Assuming the patch has `[HarmonyAfter(["x753.Mimics"])]` ofc)

**Comment by DaXcess** [comment]
According to the Harmony docs that `HarmonyAfter` *should* have worked. I don't know however how Harmony implements this.

**Comment by NickDuijndam** [comment]
I just tried by removing the dependency from `LCVRPatch` and `Plugin.cs` and harmony _does_ actully run the patches in the correct order that way. The only downside of this approach is that the patch will also be ran when the mod is not installed, which causes an exception to be printed to the console whenever the patch is ran.

**Comment by DaXcess** [comment]
Okay I did some experimenting. This is not an issue with Harmony, but an issue with **BepInEx**. It seems that during the loading/mod initialization phase, only the currently loaded mods are available in the Chainloader. This means that the mod has no clue that the Mimics mod is even present at all, and will refuse to apply patches.

I am just going to wrap the list of soft dependencies inside of a region to prepare for when it might grow too large.

**Pull request merged**
