### PR TITLE
Decouple body from head rotation

### PR DESCRIPTION
**Pull request by Phil25**
Small set of changes to make the horizontal camera movement not move the entire body at all times. This allows for more natural gestures where you look to the side or shake your head.

The body rotates if:
1. the player physically moves, or
2. the player camera rotates beyond a specified threshold.

There are some things still left to do:
- [x] Turning should be smoothed out.
- [ ] Camera rotation-to-body threshold should probably be configurable.
- [ ] I kinda want to make special animations (mostly using the computer) work with this, so other players can see you look around. I think the animation overrides the head movement but haven't looked into it yet.

Tested online:

https://github.com/DaXcess/LCVR/assets/16500675/54198c2d-e225-47c9-a469-e2df054ba58d

### CODE REVIEW

**Comment by Phil25** [comment]
Smooth player rotation was the most important thing missing I think (not shown in the video, tested locally with the mirror mod), so imma mark this as ready for review.

**Comment by DaXcess** [comment]
Oh this looks sick! I'll play around with it later today and if all looks good will merge it.

**Comment by DaXcess** [comment]
@Phil25 Unfortunately had to revert this change, since it was causing issues. For more see #154.

**Comment by Phil25** [comment]
I see, I haven’t noticed any head and camera desync, what kind of visual issues were there?

As for walking, it’s true that the body needs some time to turn to match camera direction and I adjusted the turn speed thinking it was fast enough. It can be sped up more by setting `turnWeightSharp` higher to the point where the body instantly snaps forward the frame the player moves.

This makes the body act exactly the same as before the change, at the cost of instant turns which I think looks a bit weird. I could work on exposing this setting to the config.

**Comment by DaXcess** [comment]
> I see, I haven’t noticed any head and camera desync, what kind of visual issues were there?
> 
> As for walking, it’s true that the body needs some time to turn to match camera direction and I adjusted the turn speed thinking it was fast enough. It can be sped up more by setting `turnWeightSharp` higher to the point where the body instantly snaps forward the frame the player moves.
> 
> This makes the body act exactly the same as before the change, at the cost of instant turns which I think looks a bit weird. I could work on exposing this setting to the config.

For the visual issues, it was some kind of desync between the real life head rotation and the in-game head rotation. It's quite difficult to explain, it is best observed by playing around with the MirrorDecor mod where it's a whole lot more evident.

I think the moving to the wrong angle is my mistake, as I only moved for a veery short time (like 0.1 units) which probably didn't snap the player. Also kinda sucks that in GitHub when reverting a PR there's no way to re-open the original, since I didn't want it to be gone outright, just some additional fixes.

**Comment by Phil25** [comment]
I was using the mirror mod to test it too, seemed fine on my end 🤔

And the movement detection can be a bit improved too, maybe it’s just a matter of lowering the threshold to check how much the position changed. Or I could try to check if movement keys were pressed instead.

I went with origin difference in case the player was sliding down a hill with no input or something. Though thinking about it again, rotating the body is not that important in that case.

I’ll jump into testing again and see if I can notice anything unusual. But let me know if there are some other issues to fix. I’m really hoping to see this in game, or at least have it available as an option. 🙂

**Comment by DaXcess** [comment]
The head offset seems to be caused by the snap/smooth turning offsets and is independent from your patch, time to revert the revert lol

**Comment by Phil25** [comment]
Oh alright nice xd

**Pull request merged**
